name: leave_management_app
version: 1.0.2+11
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  pin_code_fields: ^7.4.0
  fluttertoast: 8.1.2
  get_storage: 2.0.3
  flutter_launcher_icons: 0.11.0
  intl: ^0.18.0
  google_fonts: ^3.0.1
  geolocator: ^9.0.2
  infinite_scroll_pagination: ^3.2.0
  image_picker: 0.8.6+1
  syncfusion_flutter_calendar: 20.4.44
  liquid_progress_indicator: ^0.4.0
  local_auth: 2.1.3
  
  flutter: 
    sdk: flutter
  
  circular_bottom_navigation: ^2.3.0
  csv: ^5.0.1
  path_provider: ^2.0.14

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter_icons: 
  android: launcher_icon
  image_path: assets/images/MagadhLogo.png
  ios: true
  min_sdk_android: 21

flutter: 
  assets: 
    - assets/images/
  uses-material-design: true

